// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRSYj8PtJISNdwRfmIcsdZFQQlXBczgE',
    appId: '1:182026358902:web:04665ab0ac63e3242d4f57',
    messagingSenderId: '182026358902',
    projectId: 'football-0101',
    authDomain: 'football-0101.firebaseapp.com',
    storageBucket: 'football-0101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuyL_qTTHq6xuv4pCwEon1CniLOJZ0zd0',
    appId: '1:182026358902:android:28fcc96ada432ed82d4f57',
    messagingSenderId: '182026358902',
    projectId: 'football-0101',
    storageBucket: 'football-0101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPkNKq1PX2N9Avk6ZvvnJAO1SQuCq6oU',
    appId: '1:182026358902:ios:784968cac88292df2d4f57',
    messagingSenderId: '182026358902',
    projectId: 'football-0101',
    storageBucket: 'football-0101.appspot.com',
    iosBundleId: 'com.example.footballShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzPkNKq1PX2N9Avk6ZvvnJAO1SQuCq6oU',
    appId: '1:182026358902:ios:784968cac88292df2d4f57',
    messagingSenderId: '182026358902',
    projectId: 'football-0101',
    storageBucket: 'football-0101.appspot.com',
    iosBundleId: 'com.example.footballShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgRSYj8PtJISNdwRfmIcsdZFQQlXBczgE',
    appId: '1:182026358902:web:12a188a3e8795dc32d4f57',
    messagingSenderId: '182026358902',
    projectId: 'football-0101',
    authDomain: 'football-0101.firebaseapp.com',
    storageBucket: 'football-0101.appspot.com',
  );
}
